Add IServiceSelector to exported index file
superfaceai/one-sdk-js pull request #196
Opened 2022-01-19 12:57 UTC by janhalama

## Description

This PR adds IServiceSelector to exported index file.

## Motivation and Context

We need to work with IServiceSelector in @superfaceai/testing library.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the documentation accordingly. If you are changing **code related to user secrets** you need to really make sure that [security documentation](https://github.com/superfaceai/one-sdk-js/blob/main/SECURITY.md) is correct.
- [x] I have read the [CONTRIBUTING](https://github.com/superfaceai/one-sdk-js/blob/main/CONTRIBUTING.md) document.
- [x] I haven't repeated the code. (DRY)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-01-20 07:57 UTC, lukas-valenta commented
I'm not sure we want to make stuff for testing library public anymore. What about creating a `src/private/index.ts`, exporting it from there and importing from `@superfaceai/one-sdk/private` in testing lib?

2022-01-20 13:05 UTC, janhalama commented
> I'm not sure we want to make stuff for testing library public anymore. What about creating a `src/private/index.ts`, exporting it from there and importing from `@superfaceai/one-sdk/private` in testing lib?

I just have to figure out how to configure multiple exports.

2022-01-21 08:54 UTC, lukas-valenta commented
it's okay to import `@superfaceai/one-sdk/dist/private` if it would be difficult to configure

2022-02-14 09:13 UTC, lukas-valenta requested changes

2022-02-14 09:13 UTC, lukas-valenta commented on src/index.ts
> +export * from './private';
don't export this

2022-02-14 09:17 UTC, lukas-valenta approved these changes

2022-02-14 09:49 UTC, merged